import Navbar from "@/components/bars/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="h-screen grid items-center p-20"> */}
        {/* <div className="border border-tailwindLightBlue h-full rounded-lg w-full m-auto items-center relative"> */}
        {/* <div className="bg-tailwindLightBlue absolute top-0 left-0 right-0 h-12 p-2 text-2xl font-semibold">
            Admin
          </div> */}
        <Navbar />
        <div className=" mt-16 w-5/6 m-auto">{children}</div>

        {/* </div> */}
        {/* </div> */}
      </body>
    </html>
  );
}
